name: Deploy to Github

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  distribute:
    name: Distribute apk to Github
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'gradle'

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Extract Version
        run: |
          echo "VERSION_NAME=$(./gradlew -q printVersionInformation)" >> $GITHUB_ENV

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Release
      - run: |
          gh release create $GITHUB_ENV ${{ steps.sign_app.outputs.signedReleaseFile }}
